[package]
name = "extra-cpp-bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib", "rlib", "cdylib"]

[dependencies]
anyhow = "1"
cxx = "1"
ethers-core = { git = "https://github.com/gakonst/ethers-rs", rev = "0a031417d8ec9e8696229eb5d172f7155ec3c79c" }
ethers-etherscan = { git = "https://github.com/gakonst/ethers-rs", rev = "0a031417d8ec9e8696229eb5d172f7155ec3c79c" }
reqwest =  { version = "0.11", features = ["json", "blocking"] }
serde = "1"
serde_json = { version = "1", features = ["arbitrary_precision"] }
thiserror = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
defi-wallet-connect= { path="../wallet-connect" }
url = { version = "2", features = ["serde"] }
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "0a031417d8ec9e8696229eb5d172f7155ec3c79c" }
hex="0.4.3"

[build-dependencies]
# Wait until https://github.com/dtolnay/cxx/pull/1048 is merged or similar solution is found
cxx-build = { git = "https://github.com/crypto-com/cxx.git", rev = "42b011184b6d5a593cd7513edb1d554e0f086a0f", features=["doxygen"] }
