name: Android Build CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
    tags:
      - "v*.*.*"
  merge_group:
  pull_request:
    paths-ignore:
      - README.md
jobs:
  build-android:
    runs-on: macos-11
    strategy:
      matrix:
        # 21.4.7075529 is needed for Unreal Engine 4.26
        ndk_version: [25.1.8937393, 21.4.7075529]
        # TODO: is x86_64-linux-android necessary to test on CI?
        target: [armv7-linux-androideabi, aarch64-linux-android, x86_64-linux-android]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/android
        with:
          ndk_version: ${{ matrix.ndk_version }}
          target: ${{ matrix.target }}
