name: Security Audit
on:
  pull_request:
    paths:
      - Cargo.lock
  push:
    branches:
      - main
    paths:
      - Cargo.lock
  schedule:
    - cron: '0 0 * * *'

jobs:
  security_audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo audit
        run: cargo install cargo-audit
      - run: cargo audit --deny warnings
