name: Mac Build CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
    tags:
      - "v*.*.*"
  pull_request:
    paths-ignore:
      - README.md

jobs:
  mac-build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Add target x86_64-apple-darwin
        run: rustup target add x86_64-apple-darwin

      - name: Build play-cpp-sdk library
        run: ./checkmac.sh && cargo build --package play-cpp-sdk --release --target x86_64-apple-darwin

      - name: Test building demo project
        working-directory: demo
        run: make x86_64_build_test

      - name: Build demo project
        working-directory: demo
        run: make x86_64_build

      - name: Pack binaries and bindings
        run: |
          PLATFORM="$(uname -s)_x86_64"
          BUILD_TYPE="tarball"
          mkdir -p build
          cp -r demo/include build
          cp -r demo/lib build
          cp ./LICENSE build
          cp ./CHANGELOG.md build
          cd build
          install_name_tool -id @rpath/libplay_cpp_sdk.dylib ./lib/libplay_cpp_sdk.dylib
          otool -L ./lib/libplay_cpp_sdk.dylib
          tar zcvf ../play_cpp_sdk_${PLATFORM}.tar.gz *
          cd ..
          shasum -a 256 *.tar.gz > "checksums-$PLATFORM.txt"
          echo "release_file=play_cpp_sdk_$PLATFORM.tar.gz" >> $GITHUB_ENV
          echo "checksum_file=checksums-$PLATFORM.txt" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Upload binaries and bindings to Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            ${{ env.release_file }}
            ${{ env.checksum_file }}
