name: integration tests
on:
  push:
    branches:
      - main
      - release/**
    paths-ignore:
      - README.md
    tags:
      - "*"
  pull_request:
    paths-ignore:
      - README.md

jobs:
  integration_tests:
    runs-on: ubuntu-20.04
    env:
      WASM_BINDGEN_TEST_TIMEOUT: 60
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v15
      - uses: cachix/cachix-action@v10
        with:
          name: cronos
          extraPullNames: dapp
          # github don't pass secrets for pull request from fork repos,
          # in that case the push is disabled naturally.
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: 'Tar debug files'
        if: failure()
        run: tar cfz debug_files.tar.gz -C /tmp/pytest-of-runner .
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: debug-files
          path: debug_files.tar.gz
          if-no-files-found: ignore

      - name: Build play-cpp-sdk library
        run: CXX=clang++-10 CXXFLAGS=-stdlib=libc++ cargo build --package play-cpp-sdk --release

      - name: Build demo project
        working-directory: demo
        run: make CXX=clang++-10

      - name: Run cpp tests
        env:
          CRONOSCAN_API_KEY: ${{ secrets.CRONOSCAN_API_KEY }}
          PAY_API_KEY: ${{ secrets.PAY_API_KEY }}
          PAY_WEBSOCKET_PORT: "4567"
        run: ./integration_test.sh
