name: Windows Build CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        submodules: recursive
    - run: git config --global core.symlinks true

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build play-cpp-sdk crate
      shell: bash
      run: cargo build --package play-cpp-sdk --release

    - name: Collect cxxbrdiges files into demo
      shell: bash
      working-directory: demo
      run: python3 helper.py --target_dir ../target/release

    - name: Build demo project
      working-directory: .\demo
      run: msbuild .\demo.vcxproj -t:rebuild -property:Configuration=Release /p:Platform=x64
