name: Windows Build CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
    tags:
      - "v*.*.*"
  merge_group:
  pull_request:
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86_64
        toolset: 14.29
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - run: git config --global core.symlinks true

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build play-cpp-sdk crate
      run: cargo build --package play-cpp-sdk --release

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Build demo solution
      working-directory: demo
      run: msbuild .\demo.sln -t:rebuild -property:Configuration=Release /p:Platform=x64

    - name: Build demo with cmake
      working-directory: demo
      run: |
        cmake.exe `
            -B "out\build\x64-Release" `
            -G "Ninja" `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_INSTALL_PREFIX:PATH="out\install\x64-Release" `
            -DCMAKE_C_COMPILER="cl.exe" `
            -DCMAKE_CXX_COMPILER="cl.exe" `
            -DCMAKE_MAKE_PROGRAM="ninja.exe" `
            .
        cd out\build\x64-Release
        ninja

    - name: Pack binaries and bindings
      shell: bash
      run: |
        PLATFORM="Windows_x86_64"
        mkdir -p install
        cp -r demo/sdk install
        cp ./LICENSE install/sdk
        cp ./CHANGELOG.md install/sdk
        cd install
        7z a -tzip ../play_cpp_sdk_${PLATFORM}.zip *
        cd ..
        sha256sum *.zip > "checksums-$PLATFORM.txt"
        echo "release_file=play_cpp_sdk_$PLATFORM.zip" >> $GITHUB_ENV
        echo "checksum_file=checksums-$PLATFORM.txt" >> $GITHUB_ENV
        cat $GITHUB_ENV

    - name: Upload binaries and bindings to Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          ${{ env.release_file }}
          ${{ env.checksum_file }}
